"use client";
import { Canvas, useFrame } from "@react-three/fiber";
import { Float, Stars, Line } from "@react-three/drei";
import { useEffect,useRef } from "react";
import * as THREE from "three";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

function Node({p=[0,0,0] as [number,number,number],hot=false}){return <mesh position={p}><sphereGeometry args={[.075,16,16]}/><meshStandardMaterial color={hot?"#ff6a00":"#9ca3af"} emissive={hot?"#ff4d00":"#111827"} emissiveIntensity={hot?3:.4} metalness={.5}/></mesh>}
function DataPath({points}:{points:[number,number,number][]}){return <Line points={points} color="#ff6a00" lineWidth={.7} transparent opacity={.35}/>}
function InfrastructureEngine(){
 const root=useRef<THREE.Group>(null),cpu=useRef<THREE.Group>(null),cloud=useRef<THREE.Group>(null),ai=useRef<THREE.Group>(null),security=useRef<THREE.Group>(null);
 useFrame((state,d)=>{if(root.current)root.current.rotation.y+=d*.025;if(security.current)security.current.rotation.z-=d*.08});
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const groups=[cpu.current,cloud.current,ai.current,security.current].filter(Boolean) as THREE.Group[];groups.forEach((g,i)=>{g.visible=i===0;g.scale.setScalar(i===0?1:0.55)});
 const ctx=gsap.context(()=>{gsap.utils.toArray<HTMLElement>(".scene-trigger").forEach((el,i)=>{const active=groups[i];if(!active)return;ScrollTrigger.create({trigger:el,start:"top 62%",end:"bottom 38%",onEnter:()=>show(i),onEnterBack:()=>show(i)});const show=(idx:number)=>{groups.forEach((g,j)=>{if(j===idx){g.visible=true;gsap.fromTo(g.scale,{x:.62,y:.62,z:.62},{x:1.18,y:1.18,z:1.18,duration:.75,ease:"power3.out"});gsap.to(g.rotation,{y:idx*.45,duration:1})}else{gsap.to(g.scale,{x:.35,y:.35,z:.35,duration:.35,onComplete:()=>{g.visible=false}})}})}});gsap.utils.toArray<HTMLElement>(".work-trigger,.process-trigger").forEach(el=>ScrollTrigger.create({trigger:el,start:"top 60%",onEnter:()=>groups.forEach(g=>g.visible=false),onEnterBack:()=>groups.forEach(g=>g.visible=false)}))});return()=>ctx.revert()},[]);
 return <group ref={root} position={[2.15,.05,0]} rotation={[.12,-.18,0]} scale={1.18}>
  <group ref={cpu}><mesh><boxGeometry args={[2.2,2.2,.28]}/><meshStandardMaterial color="#0b0d12" metalness={.95} roughness={.16}/></mesh><mesh position={[0,0,.2]}><boxGeometry args={[1.15,1.15,.15]}/><meshStandardMaterial color="#ff6a00" emissive="#7a2200" emissiveIntensity={1.2} metalness={.85}/></mesh>{[[-.75,.75],[.75,.75],[-.75,-.75],[.75,-.75]].map(([x,y],i)=><Node key={i} p={[x,y,.2]} hot={i===0}/>)}</group>
  <group ref={cloud}>{[-.75,0,.75].map((x,i)=><group key={i} position={[x,0,i*.16]}><mesh><boxGeometry args={[.55,2.1,.6]}/><meshStandardMaterial color="#151922" metalness={.88} roughness={.22}/></mesh>{[-.65,0,.65].map((y,j)=><Node key={j} p={[0,y,.34]} hot={i===1&&j===1}/>)}</group>)}<DataPath points={[[ -1.2,0,.4],[1.2,0,.4]]}/></group>
  <group ref={ai}>{Array.from({length:14}).map((_,i)=>{const a=i/14*Math.PI*2,r=i%3===0?1.35:.85;return <Node key={i} p={[Math.cos(a)*r,Math.sin(a)*r,(i%2)*.25]} hot={i%4===0}/>})}<DataPath points={[[-1.2,.2,.1],[-.35,.8,.25],[.55,.55,.1],[1.2,-.15,.25],[.2,-.9,.1],[-1.2,.2,.1]]}/><DataPath points={[[0,1.2,.1],[.65,.1,.25],[-.6,-.55,.1],[0,1.2,.1]]}/></group>
  <group ref={security}><mesh><icosahedronGeometry args={[1.05,1]}/><meshStandardMaterial color="#11151c" wireframe metalness={1}/></mesh>{[1.3,1.6,1.9].map((r,i)=><mesh key={i} rotation={[i*.65,i*.35,Math.PI/4]}><torusGeometry args={[r,.035,10,64]}/><meshStandardMaterial color={i===1?"#ff6a00":"#59606c"} emissive={i===1?"#6b2000":"#000"} emissiveIntensity={1.2} metalness={1}/></mesh>)}</group>
 </group>
}
export default function ImmersiveHero(){
 const root=useRef<HTMLElement>(null);
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{gsap.to(".hero-copy",{opacity:0,y:-90,scrollTrigger:{trigger:root.current,start:"top top",end:"48% top",scrub:true}});gsap.fromTo(".system-label",{opacity:0},{opacity:1,scrollTrigger:{trigger:root.current,start:"25% top",end:"45% top",scrub:true}})},root);return()=>ctx.revert()},[]);
 return <section ref={root} id="system-story" className="hero persistent-world"><div className="canvas-wrap persistent-canvas" aria-hidden="true"><Canvas dpr={[1,1.5]} camera={{position:[0,0,7.4],fov:36}} gl={{antialias:true,powerPreference:"high-performance"}}><color attach="background" args={["#050608"]}/><fog attach="fog" args={["#050608",8,17]}/><ambientLight intensity={.45}/><directionalLight position={[4,5,6]} intensity={3}/><pointLight position={[-3,-2,4]} color="#ff6a00" intensity={30}/><Stars radius={70} depth={45} count={450} factor={1.4} fade speed={.2}/><Float speed={.7} rotationIntensity={.06} floatIntensity={.18}><InfrastructureEngine/></Float></Canvas></div><div className="system-label"><span>LIVE SYSTEM / 01</span><b>SOFTWARE</b><b>CLOUD</b><b>INTELLIGENCE</b><b>SECURITY</b></div><div className="hero-copy"><p className="eyebrow">TEXCORTECH / DIGITAL ENGINEERING</p><h1>Systems that<br/><span>move business.</span></h1><p className="lede">We engineer connected digital products—from interface to infrastructure, intelligence and security.</p><a className="hero-cta" href="#capabilities">Explore the system <b>↘</b></a><div className="scroll-cue">SCROLL TO DECONSTRUCT <i/></div></div></section>
}